name: has_wifi_rtt
description: A flutter plugin package to check whether device has Wi-Fi RTT Scan Feature or not.
version: 1.0.0
homepage: https://github.com/baranacikgoz/has_wifi_rtt

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.has_wifi_rtt
        pluginClass: HasWifiRttPlugin

